version: "0.0"

services:
  activemq:
    environment:
      ## Required system variables ##
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    build:
      context: .
      dockerfile: Dockerfile.template
#    network_mode: "host"   Leave it off the host network to keep it private behind APIs
    ports:
      - "8161:8161"
      - "61611:61611"
      - "61612:61612"
      - "61613:61613"
    restart: always
    volumes:
      - 'resin-data:/activemq_conf'
    labels:
      io.balena.features.dbus: "1"
    cap_add:
    privileged: true
